spring:
  application:
    name: vkBot
#server:
#  port: 3334
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

token:
  confirmation: #строка, которую должен вернуть сервер
  access: #ключ доступа

secret:
  key: #секретный ключ

server:
  port: #ваш порт