token:
  confirmation: 1484696a #строка, которую должен вернуть сервер
  access: vk1.a.WiWQtdgHoRFLwW03ePIaLHEFSZRXtEPaGgHNrQKE9OxU8entmFq91BYMJXsODvocmagogQpwDnsrqknIyo3M_o4dTokLalNhm2EuEhVGvrGV7sQCfj5xoac5UwDYVwQIT6Y5XtHligv6C8LNOYSmF6CMU9rrbalhvssAK4bmU1cHYlIonpf34WEDasv0eYsMOdqMLx8R8naNUh_Mc9Jefg #ключ доступа

secret:
  key: kjhgiyfjfhg #секретный ключ

server:
  port: 3334 #ваш порт

spring:
  application:
    name: vkBot
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true